### ISSUE TITLE
JS Partials Not Compiling

### ISSUE THREAD

**Issue by kevrowe** [truedigital/frontend#8]
[/gulp/settings/paths.js:26](https://github.com/truedigital/frontend/blob/master/gulp/settings/paths.js#L26)

Change:
`partials: path.join(_baseDir, '/js/partials'),`
to
`partials: path.join(_baseDir, '/js/partials/**'),`

**Comment by craigcoles** [comment]
Appears this was fixed in this commit - https://github.com/truedigital/frontend/commit/ce16b1d4633a0482562d3978e38d3bf17f96920a.

Forgot to reference this issue... 

![](http://gifsec.com/wp-content/uploads/GIF/2014/10/OMG-Facepalm-GIF.gif?gs=a)
